//        THIS WONT DO ANYTHING, THIS IS HERE TO STOP THE BOT FROM GOING OFFLINE DUE TO "TYPING_START.ts was not found" OR SOMETHING ALONG THOSE LINES, IF YOU WANT SOMETHING "SPECIAL" TO HAPPEN MAKE A PULL REQUEST WITH A VALID CODE

export default function() {
	// console.log('Typing started')
}
